var searchData=
[
  ['image_24237',['Image',['../classvk_1_1Image.html',1,'vk::Image'],['../classvk_1_1raii_1_1Image.html',1,'vk::raii::Image']]],
  ['imageblit_24238',['ImageBlit',['../structvk_1_1ImageBlit.html',1,'vk']]],
  ['imageblit2_24239',['ImageBlit2',['../structvk_1_1ImageBlit2.html',1,'vk']]],
  ['imagecapturedescriptordatainfoext_24240',['ImageCaptureDescriptorDataInfoEXT',['../structvk_1_1ImageCaptureDescriptorDataInfoEXT.html',1,'vk']]],
  ['imagecompressioncontrolext_24241',['ImageCompressionControlEXT',['../structvk_1_1ImageCompressionControlEXT.html',1,'vk']]],
  ['imagecompressionpropertiesext_24242',['ImageCompressionPropertiesEXT',['../structvk_1_1ImageCompressionPropertiesEXT.html',1,'vk']]],
  ['imagecopy_24243',['ImageCopy',['../structvk_1_1ImageCopy.html',1,'vk']]],
  ['imagecopy2_24244',['ImageCopy2',['../structvk_1_1ImageCopy2.html',1,'vk']]],
  ['imagecreateinfo_24245',['ImageCreateInfo',['../structvk_1_1ImageCreateInfo.html',1,'vk']]],
  ['imagedata_24246',['ImageData',['../structvk_1_1su_1_1ImageData.html',1,'vk::su']]],
  ['imagedrmformatmodifierexplicitcreateinfoext_24247',['ImageDrmFormatModifierExplicitCreateInfoEXT',['../structvk_1_1ImageDrmFormatModifierExplicitCreateInfoEXT.html',1,'vk']]],
  ['imagedrmformatmodifierlistcreateinfoext_24248',['ImageDrmFormatModifierListCreateInfoEXT',['../structvk_1_1ImageDrmFormatModifierListCreateInfoEXT.html',1,'vk']]],
  ['imagedrmformatmodifierpropertiesext_24249',['ImageDrmFormatModifierPropertiesEXT',['../structvk_1_1ImageDrmFormatModifierPropertiesEXT.html',1,'vk']]],
  ['imageformatlistcreateinfo_24250',['ImageFormatListCreateInfo',['../structvk_1_1ImageFormatListCreateInfo.html',1,'vk']]],
  ['imageformatproperties_24251',['ImageFormatProperties',['../structvk_1_1ImageFormatProperties.html',1,'vk']]],
  ['imageformatproperties2_24252',['ImageFormatProperties2',['../structvk_1_1ImageFormatProperties2.html',1,'vk']]],
  ['imagememorybarrier_24253',['ImageMemoryBarrier',['../structvk_1_1ImageMemoryBarrier.html',1,'vk']]],
  ['imagememorybarrier2_24254',['ImageMemoryBarrier2',['../structvk_1_1ImageMemoryBarrier2.html',1,'vk']]],
  ['imagememoryrequirementsinfo2_24255',['ImageMemoryRequirementsInfo2',['../structvk_1_1ImageMemoryRequirementsInfo2.html',1,'vk']]],
  ['imageplanememoryrequirementsinfo_24256',['ImagePlaneMemoryRequirementsInfo',['../structvk_1_1ImagePlaneMemoryRequirementsInfo.html',1,'vk']]],
  ['imageresolve_24257',['ImageResolve',['../structvk_1_1ImageResolve.html',1,'vk']]],
  ['imageresolve2_24258',['ImageResolve2',['../structvk_1_1ImageResolve2.html',1,'vk']]],
  ['imagesparsememoryrequirementsinfo2_24259',['ImageSparseMemoryRequirementsInfo2',['../structvk_1_1ImageSparseMemoryRequirementsInfo2.html',1,'vk']]],
  ['imagestencilusagecreateinfo_24260',['ImageStencilUsageCreateInfo',['../structvk_1_1ImageStencilUsageCreateInfo.html',1,'vk']]],
  ['imagesubresource_24261',['ImageSubresource',['../structvk_1_1ImageSubresource.html',1,'vk']]],
  ['imagesubresource2khr_24262',['ImageSubresource2KHR',['../structvk_1_1ImageSubresource2KHR.html',1,'vk']]],
  ['imagesubresourcelayers_24263',['ImageSubresourceLayers',['../structvk_1_1ImageSubresourceLayers.html',1,'vk']]],
  ['imagesubresourcerange_24264',['ImageSubresourceRange',['../structvk_1_1ImageSubresourceRange.html',1,'vk']]],
  ['imageswapchaincreateinfokhr_24265',['ImageSwapchainCreateInfoKHR',['../structvk_1_1ImageSwapchainCreateInfoKHR.html',1,'vk']]],
  ['imagetomemorycopyext_24266',['ImageToMemoryCopyEXT',['../structvk_1_1ImageToMemoryCopyEXT.html',1,'vk']]],
  ['imageusagenotsupportedkhrerror_24267',['ImageUsageNotSupportedKHRError',['../classvk_1_1ImageUsageNotSupportedKHRError.html',1,'vk']]],
  ['imageview_24268',['ImageView',['../classvk_1_1ImageView.html',1,'vk::ImageView'],['../classvk_1_1raii_1_1ImageView.html',1,'vk::raii::ImageView']]],
  ['imageviewaddresspropertiesnvx_24269',['ImageViewAddressPropertiesNVX',['../structvk_1_1ImageViewAddressPropertiesNVX.html',1,'vk']]],
  ['imageviewastcdecodemodeext_24270',['ImageViewASTCDecodeModeEXT',['../structvk_1_1ImageViewASTCDecodeModeEXT.html',1,'vk']]],
  ['imageviewcapturedescriptordatainfoext_24271',['ImageViewCaptureDescriptorDataInfoEXT',['../structvk_1_1ImageViewCaptureDescriptorDataInfoEXT.html',1,'vk']]],
  ['imageviewcreateinfo_24272',['ImageViewCreateInfo',['../structvk_1_1ImageViewCreateInfo.html',1,'vk']]],
  ['imageviewhandleinfonvx_24273',['ImageViewHandleInfoNVX',['../structvk_1_1ImageViewHandleInfoNVX.html',1,'vk']]],
  ['imageviewminlodcreateinfoext_24274',['ImageViewMinLodCreateInfoEXT',['../structvk_1_1ImageViewMinLodCreateInfoEXT.html',1,'vk']]],
  ['imageviewsampleweightcreateinfoqcom_24275',['ImageViewSampleWeightCreateInfoQCOM',['../structvk_1_1ImageViewSampleWeightCreateInfoQCOM.html',1,'vk']]],
  ['imageviewslicedcreateinfoext_24276',['ImageViewSlicedCreateInfoEXT',['../structvk_1_1ImageViewSlicedCreateInfoEXT.html',1,'vk']]],
  ['imageviewusagecreateinfo_24277',['ImageViewUsageCreateInfo',['../structvk_1_1ImageViewUsageCreateInfo.html',1,'vk']]],
  ['importfencefdinfokhr_24278',['ImportFenceFdInfoKHR',['../structvk_1_1ImportFenceFdInfoKHR.html',1,'vk']]],
  ['importmemoryfdinfokhr_24279',['ImportMemoryFdInfoKHR',['../structvk_1_1ImportMemoryFdInfoKHR.html',1,'vk']]],
  ['importmemoryhostpointerinfoext_24280',['ImportMemoryHostPointerInfoEXT',['../structvk_1_1ImportMemoryHostPointerInfoEXT.html',1,'vk']]],
  ['importsemaphorefdinfokhr_24281',['ImportSemaphoreFdInfoKHR',['../structvk_1_1ImportSemaphoreFdInfoKHR.html',1,'vk']]],
  ['incompatibledisplaykhrerror_24282',['IncompatibleDisplayKHRError',['../classvk_1_1IncompatibleDisplayKHRError.html',1,'vk']]],
  ['incompatibledrivererror_24283',['IncompatibleDriverError',['../classvk_1_1IncompatibleDriverError.html',1,'vk']]],
  ['incompatibleshaderbinaryexterror_24284',['IncompatibleShaderBinaryEXTError',['../classvk_1_1IncompatibleShaderBinaryEXTError.html',1,'vk']]],
  ['indextypevalue_24285',['IndexTypeValue',['../structvk_1_1IndexTypeValue.html',1,'vk']]],
  ['indextypevalue_3c_20uint16_5ft_20_3e_24286',['IndexTypeValue&lt; uint16_t &gt;',['../structvk_1_1IndexTypeValue_3_01uint16__t_01_4.html',1,'vk']]],
  ['indextypevalue_3c_20uint32_5ft_20_3e_24287',['IndexTypeValue&lt; uint32_t &gt;',['../structvk_1_1IndexTypeValue_3_01uint32__t_01_4.html',1,'vk']]],
  ['indextypevalue_3c_20uint8_5ft_20_3e_24288',['IndexTypeValue&lt; uint8_t &gt;',['../structvk_1_1IndexTypeValue_3_01uint8__t_01_4.html',1,'vk']]],
  ['indirectcommandslayoutcreateinfonv_24289',['IndirectCommandsLayoutCreateInfoNV',['../structvk_1_1IndirectCommandsLayoutCreateInfoNV.html',1,'vk']]],
  ['indirectcommandslayoutnv_24290',['IndirectCommandsLayoutNV',['../classvk_1_1IndirectCommandsLayoutNV.html',1,'vk::IndirectCommandsLayoutNV'],['../classvk_1_1raii_1_1IndirectCommandsLayoutNV.html',1,'vk::raii::IndirectCommandsLayoutNV']]],
  ['indirectcommandslayouttokennv_24291',['IndirectCommandsLayoutTokenNV',['../structvk_1_1IndirectCommandsLayoutTokenNV.html',1,'vk']]],
  ['indirectcommandsstreamnv_24292',['IndirectCommandsStreamNV',['../structvk_1_1IndirectCommandsStreamNV.html',1,'vk']]],
  ['initializationfailederror_24293',['InitializationFailedError',['../classvk_1_1InitializationFailedError.html',1,'vk']]],
  ['initializeperformanceapiinfointel_24294',['InitializePerformanceApiInfoINTEL',['../structvk_1_1InitializePerformanceApiInfoINTEL.html',1,'vk']]],
  ['inputattachmentaspectreference_24295',['InputAttachmentAspectReference',['../structvk_1_1InputAttachmentAspectReference.html',1,'vk']]],
  ['instance_24296',['Instance',['../classvk_1_1Instance.html',1,'vk::Instance'],['../classvk_1_1raii_1_1Instance.html',1,'vk::raii::Instance']]],
  ['instancecreateinfo_24297',['InstanceCreateInfo',['../structvk_1_1InstanceCreateInfo.html',1,'vk']]],
  ['instancedispatcher_24298',['InstanceDispatcher',['../classvk_1_1raii_1_1InstanceDispatcher.html',1,'vk::raii']]],
  ['invaliddrmformatmodifierplanelayoutexterror_24299',['InvalidDrmFormatModifierPlaneLayoutEXTError',['../classvk_1_1InvalidDrmFormatModifierPlaneLayoutEXTError.html',1,'vk']]],
  ['invalidexternalhandleerror_24300',['InvalidExternalHandleError',['../classvk_1_1InvalidExternalHandleError.html',1,'vk']]],
  ['invalidopaquecaptureaddresserror_24301',['InvalidOpaqueCaptureAddressError',['../classvk_1_1InvalidOpaqueCaptureAddressError.html',1,'vk']]],
  ['invalidshadernverror_24302',['InvalidShaderNVError',['../classvk_1_1InvalidShaderNVError.html',1,'vk']]],
  ['invalidvideostdparameterskhrerror_24303',['InvalidVideoStdParametersKHRError',['../classvk_1_1InvalidVideoStdParametersKHRError.html',1,'vk']]],
  ['is_5ferror_5fcode_5fenum_3c_20vk_3a_3aresult_20_3e_24304',['is_error_code_enum&lt; vk::Result &gt;',['../structstd_1_1is__error__code__enum_3_01vk_1_1Result_01_4.html',1,'std']]],
  ['ispartofstructurechain_24305',['IsPartOfStructureChain',['../structvk_1_1IsPartOfStructureChain.html',1,'vk']]],
  ['ispartofstructurechain_3c_20type_2c_20head_2c_20tail_2e_2e_2e_20_3e_24306',['IsPartOfStructureChain&lt; Type, Head, Tail... &gt;',['../structvk_1_1IsPartOfStructureChain_3_01Type_00_01Head_00_01Tail_8_8_8_01_4.html',1,'vk']]],
  ['isvulkanhandletype_24307',['isVulkanHandleType',['../structvk_1_1isVulkanHandleType.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aaccelerationstructurekhr_20_3e_24308',['isVulkanHandleType&lt; vk::AccelerationStructureKHR &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1AccelerationStructureKHR_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aaccelerationstructurenv_20_3e_24309',['isVulkanHandleType&lt; vk::AccelerationStructureNV &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1AccelerationStructureNV_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3abuffer_20_3e_24310',['isVulkanHandleType&lt; vk::Buffer &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Buffer_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3abufferview_20_3e_24311',['isVulkanHandleType&lt; vk::BufferView &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1BufferView_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3acommandbuffer_20_3e_24312',['isVulkanHandleType&lt; vk::CommandBuffer &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1CommandBuffer_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3acommandpool_20_3e_24313',['isVulkanHandleType&lt; vk::CommandPool &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1CommandPool_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3acufunctionnvx_20_3e_24314',['isVulkanHandleType&lt; vk::CuFunctionNVX &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1CuFunctionNVX_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3acumodulenvx_20_3e_24315',['isVulkanHandleType&lt; vk::CuModuleNVX &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1CuModuleNVX_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adebugreportcallbackext_20_3e_24316',['isVulkanHandleType&lt; vk::DebugReportCallbackEXT &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DebugReportCallbackEXT_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adebugutilsmessengerext_20_3e_24317',['isVulkanHandleType&lt; vk::DebugUtilsMessengerEXT &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DebugUtilsMessengerEXT_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adeferredoperationkhr_20_3e_24318',['isVulkanHandleType&lt; vk::DeferredOperationKHR &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DeferredOperationKHR_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adescriptorpool_20_3e_24319',['isVulkanHandleType&lt; vk::DescriptorPool &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DescriptorPool_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adescriptorset_20_3e_24320',['isVulkanHandleType&lt; vk::DescriptorSet &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DescriptorSet_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adescriptorsetlayout_20_3e_24321',['isVulkanHandleType&lt; vk::DescriptorSetLayout &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DescriptorSetLayout_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adescriptorupdatetemplate_20_3e_24322',['isVulkanHandleType&lt; vk::DescriptorUpdateTemplate &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DescriptorUpdateTemplate_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adevice_20_3e_24323',['isVulkanHandleType&lt; vk::Device &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Device_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adevicememory_20_3e_24324',['isVulkanHandleType&lt; vk::DeviceMemory &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DeviceMemory_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adisplaykhr_20_3e_24325',['isVulkanHandleType&lt; vk::DisplayKHR &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DisplayKHR_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3adisplaymodekhr_20_3e_24326',['isVulkanHandleType&lt; vk::DisplayModeKHR &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1DisplayModeKHR_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aevent_20_3e_24327',['isVulkanHandleType&lt; vk::Event &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Event_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3afence_20_3e_24328',['isVulkanHandleType&lt; vk::Fence &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Fence_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aframebuffer_20_3e_24329',['isVulkanHandleType&lt; vk::Framebuffer &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Framebuffer_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aimage_20_3e_24330',['isVulkanHandleType&lt; vk::Image &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Image_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aimageview_20_3e_24331',['isVulkanHandleType&lt; vk::ImageView &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1ImageView_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aindirectcommandslayoutnv_20_3e_24332',['isVulkanHandleType&lt; vk::IndirectCommandsLayoutNV &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1IndirectCommandsLayoutNV_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3ainstance_20_3e_24333',['isVulkanHandleType&lt; vk::Instance &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Instance_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3amicromapext_20_3e_24334',['isVulkanHandleType&lt; vk::MicromapEXT &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1MicromapEXT_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aopticalflowsessionnv_20_3e_24335',['isVulkanHandleType&lt; vk::OpticalFlowSessionNV &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1OpticalFlowSessionNV_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aperformanceconfigurationintel_20_3e_24336',['isVulkanHandleType&lt; vk::PerformanceConfigurationINTEL &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1PerformanceConfigurationINTEL_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aphysicaldevice_20_3e_24337',['isVulkanHandleType&lt; vk::PhysicalDevice &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1PhysicalDevice_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3apipeline_20_3e_24338',['isVulkanHandleType&lt; vk::Pipeline &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Pipeline_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3apipelinecache_20_3e_24339',['isVulkanHandleType&lt; vk::PipelineCache &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1PipelineCache_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3apipelinelayout_20_3e_24340',['isVulkanHandleType&lt; vk::PipelineLayout &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1PipelineLayout_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aprivatedataslot_20_3e_24341',['isVulkanHandleType&lt; vk::PrivateDataSlot &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1PrivateDataSlot_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aquerypool_20_3e_24342',['isVulkanHandleType&lt; vk::QueryPool &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1QueryPool_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aqueue_20_3e_24343',['isVulkanHandleType&lt; vk::Queue &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Queue_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3arenderpass_20_3e_24344',['isVulkanHandleType&lt; vk::RenderPass &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1RenderPass_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3asampler_20_3e_24345',['isVulkanHandleType&lt; vk::Sampler &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Sampler_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3asamplerycbcrconversion_20_3e_24346',['isVulkanHandleType&lt; vk::SamplerYcbcrConversion &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1SamplerYcbcrConversion_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3asemaphore_20_3e_24347',['isVulkanHandleType&lt; vk::Semaphore &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1Semaphore_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3ashaderext_20_3e_24348',['isVulkanHandleType&lt; vk::ShaderEXT &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1ShaderEXT_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3ashadermodule_20_3e_24349',['isVulkanHandleType&lt; vk::ShaderModule &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1ShaderModule_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3asurfacekhr_20_3e_24350',['isVulkanHandleType&lt; vk::SurfaceKHR &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1SurfaceKHR_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3aswapchainkhr_20_3e_24351',['isVulkanHandleType&lt; vk::SwapchainKHR &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1SwapchainKHR_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3avalidationcacheext_20_3e_24352',['isVulkanHandleType&lt; vk::ValidationCacheEXT &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1ValidationCacheEXT_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3avideosessionkhr_20_3e_24353',['isVulkanHandleType&lt; vk::VideoSessionKHR &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1VideoSessionKHR_01_4.html',1,'vk']]],
  ['isvulkanhandletype_3c_20vk_3a_3avideosessionparameterskhr_20_3e_24354',['isVulkanHandleType&lt; vk::VideoSessionParametersKHR &gt;',['../structvk_1_1isVulkanHandleType_3_01vk_1_1VideoSessionParametersKHR_01_4.html',1,'vk']]]
];
